### ISSUE TITLE
is not building on ubuntu 18.04

### ISSUE THREAD

**Issue by pinpins** [smileycoin/smileyCoin#44]
Always returns 

checking for MSG_NOSIGNAL... yes
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing

Regardless of 4.8 or 5.3 version used.

**Comment by antonva** [comment]
Hi, the build instructions are a bit out of date, smileycoin uses bdb 5.3
only. You should be able to get past this step by installing `libdb5.3++-dev`.

Until the build instructions are updated, you can use the [git workflow](https://github.com/smileycoin/smileyCoin/blob/c654c0d19692ae649baa09541b2507aa86540912/.github/workflows/smileycoin-ci.yml#L18) to see the base 
dependencies as a guideline (note: it uses ubuntu 20.04)

**Comment by pinpins** [comment]
weird


sudo apt-get install -y build-essential libdb5.3++-dev libboost-all-dev libssl-dev libtool autoconf pkg-config
libdb5.3++-dev is already the newest version (5.3.28-13.1ubuntu1.1).
libdb5.3++-dev set to manually installed.

smileyCoin$ ./configure

.....

checking for MSG_NOSIGNAL... yes
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing

**Comment by antonva** [comment]
That is odd, I'll try reproducing that in a VM in a bit.

**Comment by pinpins** [comment]
Yes, weird, answering on your query

/usr/lib/x86_64-linux-gnu$ ll libdb_cxx.so
lrwxrwxrwx 1 root root 16 Jun  3  2019 libdb_cxx.so -> libdb_cxx-5.3.so

> BDB_CFLAGS and BDB_LIBS are not implemented in the smly_find_bdb53.m4 macro yet,
This is what I have used so far for other project in case of issues with BDB

**Comment by antonva** [comment]
I've had a go at updating the macro, you can try out this [gist](https://gist.github.com/antonva/6e8ce510884ec39c13ad964dfa40ac2e)
i.e. updating `./build-aux/m4/smileycoin_find_bdb53.m4` with the contents in the gist file. 

That way you can specify both `BDB_CFLAGS` and `BDB_LIBS` if you want.
The alternative is to fall back to using  `LDFLAGS` and `CPPFLAGS` which should also work.

**Comment by pinpins** [comment]
Thanks, it helped
