### ISSUE TITLE
can't compile on linux ubuntu 20.04 with lxc containers

### ISSUE THREAD

**Issue by vvarr10r** [smileycoin/smileyCoin#91]
I've been attempting to install smileycoin on my newly formatted ubuntu machine using lxc containers but receive multiple warnings messages about unescaped sequences. 

I have documented all of the commands I use in a google document: https://uranus.eyescubed.io/tutorials/smileycoin

I would very much appreciate some assistance with installing smileycoin, perhaps someone looking over the commands I've used and clarifying? These commands should be universal, so I'm confused why they aren't working.

edit: for grammar

**Comment by gstefans** [comment]
this has been solved, right?

**Comment by vvarr10r** [comment]
compiled and installed despite warnings. tested multiple transactions with smileycoind successfully.
